# This workflow builds and pushes Docker images in docker/terraform and docker/python to GitHub Container Registry (ghcr.io)
# Make sure to set the following repository secrets:
# - GHCR_USERNAME: Your GitHub username
# - GHCR_TOKEN: A GitHub token with write:packages, read:packages, and repo scopes

name: Build and Push Docker Image to GHCR

on:
  push:
    paths:
      - 'docker/terraform/**'
      - 'docker/python/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - name: terraform
            context: ./docker/terraform
            dockerfile: ./docker/terraform/Dockerfile
            tag: terraform
          - name: python
            context: ./docker/python
            dockerfile: ./docker/python/Dockerfile
            tag: python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/devcontainer-${{ matrix.image.tag }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm64/v8